name = "iris-worker"
main = "worker.js"
compatibility_date = "2024-01-01"

kv_namespaces = [
  { binding = "iris_rag_kv", id = "a7db6bdf8bc94d6d88ec860f4c316fbd" }
]

[vars]
GEMINI_API_KEY = ""
openai_api_key = ""
ALLOWED_ORIGIN = "https://radilovk.github.io"
DEBUG = "false" # Set to "true" for detailed logging
WEB_RESEARCH_API_KEY = ""
WEB_RESEARCH_ENDPOINT = "https://serper.dev/search"

